### ISSUE TITLE
Using update.php with cPanel CronJobs

### ISSUE THREAD

**Issue by LuigiPulcini** [YahnisElsts/wp-update-server-stats#2]
I was trying to automate the db updating process using CronJobs. With the current code, CronJobs was configured as follows:
```
php /path/to/my/website/wp-update-server-stats/update.php --dir "/path/to/my/website/update/logs"
```

but CronJobs reported the following error:

```
Fatal error: Uncaught Error: Class 'Wpup\LogParserCli' not found in /path/t/my/website/wp-update-server-stats/update.php:9
Stack trace:
#0 {main}
  thrown in /path/to/my/website/wp-update-server-stats/update.php on line 9
```

So I edited line 2 of update.php as follows:

```
require dirname(__FILE__) . '/vendor/autoload.php';
```

and now update.php works in CronJobs with no errors.

**Comment by YahnisElsts** [comment]
Thank you for the report. That should be fixed now.
